const ADMIN_EMAIL="norvenofficial01@gmail.com";
const ADMIN_PASSWORD="Norven@2026";
const ADMIN_SECTIONS=[
["overview","Dashboard / Overview"],["products","Products"],["orders","Orders"],["customers","Customers"],
["reviews","Reviews"],["categories","Categories / Sub-categories"],["coupons","Coupons"],["offers","Offers"],
["homepage","Homepage Management"],["banners","Banners & Ads"],["settings","Store Settings"],["shipping","Shipping Settings"],
["payments","KYC & Payments"],["notifications","Notifications"],["returns","Return & Refund (Future)"],["security","Security / Backend"]
];
let currentSection="overview";
function isAdmin(){return sessionStorage.getItem("norven_admin_session")==="1"}
function adminLogin(){let email=$("#admin-email").value.trim(),pass=$("#admin-pass").value; if(!email||!pass)return $("#login-msg").textContent="Enter email and password."; if(email!==ADMIN_EMAIL||pass!==ADMIN_PASSWORD){$("#login-msg").textContent="Invalid admin email or password.";return} sessionStorage.setItem("norven_admin_session","1");showAdmin()}
function adminLogout(){sessionStorage.removeItem("norven_admin_session");location.reload()}
function showAdmin(){$("#login").classList.add("hide");$("#dashboard").classList.remove("hide");renderTabs();renderSection("overview");refreshStats()}
function refreshStats(){let p=products(),o=read(KEYS.orders,[]);$("#stat-products").textContent=p.length;$("#stat-orders").textContent=o.length;$("#stat-sales").textContent=money(o.filter(x=>x.order_status==="Delivered").reduce((a,x)=>a+x.total,0));$("#stat-stock").textContent=p.reduce((a,x)=>a+(+x.stock||0),0)}
function renderTabs(){$("#tabs").innerHTML=ADMIN_SECTIONS.map(([id,n])=>`<button class="btn admin-tab ${id===currentSection?"primary":""}" onclick="renderSection('${id}')">${n}</button>`).join("")}
function renderSection(id){currentSection=id;renderTabs();let f=SECTION_RENDERERS[id]||(()=>`<div class="panel"><h2>${id}</h2></div>`);$("#admin-content").innerHTML=f()}
function productRows(){return products().map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(p.sku||"")}</td><td>${money(p.price)}</td><td>${p.stock}</td><td>${p.featured?"Yes":"No"}</td><td><button class="btn" onclick="editProduct('${p.id}')">Edit</button> <button class="btn danger" onclick="deleteProduct('${p.id}')">Delete</button></td></tr>`).join("")}
function productForm(p={}){return `<div class="panel"><h3>${p.id?"Edit":"Add"} Product</h3><div class="formgrid"><input id="pf-name" class="input" placeholder="Product name" value="${esc(p.name||"")}"><input id="pf-sku" class="input" placeholder="SKU" value="${esc(p.sku||"")}"><input id="pf-price" class="input" type="number" placeholder="Price" value="${p.price||""}"><input id="pf-mrp" class="input" type="number" placeholder="MRP" value="${p.mrp||""}"><input id="pf-stock" class="input" type="number" placeholder="Stock" value="${p.stock??""}"><input id="pf-cat" class="input" placeholder="Category" value="${esc(p.category||"")}"><input id="pf-sub" class="input" placeholder="Sub-category" value="${esc(p.subcategory||"")}"><input id="pf-images" class="input full" placeholder="Image URLs, comma separated" value="${esc((p.images||[]).join(", "))}"><input id="pf-video" class="input full" placeholder="Product video URL" value="${esc(p.video_url||"")}"><textarea id="pf-desc" class="textarea full" placeholder="Description">${esc(p.description||"")}</textarea><textarea id="pf-spec" class="textarea full" placeholder='Specifications JSON, e.g. {"Material":"Cotton"}'>${esc(JSON.stringify(p.specifications||{},null,2))}</textarea><input id="pf-sizes" class="input" placeholder="Sizes: S,M,L,XL" value="${esc((p.sizes||[]).join(","))}"><input id="pf-colors" class="input" placeholder="Colors: Black,White" value="${esc((p.colors||[]).join(","))}"><input id="pf-order" class="input" type="number" placeholder="Homepage order" value="${p.homepage_order||999999}"><label><input id="pf-featured" type="checkbox" ${p.featured?"checked":""}> Featured on homepage</label></div><button class="btn primary" style="margin-top:12px" onclick="saveProduct('${p.id||""}')">Save Product</button></div>`}
function saveProduct(id){let p=products(),old=p.find(x=>x.id===id)||{id:"p"+Date.now(),active:true,rating:0,reviews_count:0};let spec={};try{spec=JSON.parse($("#pf-spec").value||"{}")}catch{alert("Specifications must be valid JSON");return}Object.assign(old,{name:$("#pf-name").value,sku:$("#pf-sku").value,price:+$("#pf-price").value,mrp:+$("#pf-mrp").value,stock:+$("#pf-stock").value,category:$("#pf-cat").value,subcategory:$("#pf-sub").value,images:$("#pf-images").value.split(",").map(x=>x.trim()).filter(Boolean),video_url:$("#pf-video").value,description:$("#pf-desc").value,specifications:spec,sizes:$("#pf-sizes").value.split(",").map(x=>x.trim()).filter(Boolean),colors:$("#pf-colors").value.split(",").map(x=>x.trim()).filter(Boolean),homepage_order:+$("#pf-order").value||999999,featured:$("#pf-featured").checked});if(!id)p.push(old);write(KEYS.products,p);renderSection("products");refreshStats()}
function editProduct(id){let p=products().find(x=>x.id===id);$("#admin-content").innerHTML=productForm(p)}
function deleteProduct(id){if(confirm("Delete product?")){write(KEYS.products,products().filter(x=>x.id!==id));renderSection("products");refreshStats()}}
const SECTION_RENDERERS={
overview:()=>`<div class="panel"><h2>Dashboard</h2><p>Control your complete NORVEN store from the sections below.</p><ul><li>Products, homepage order and featured products</li><li>Orders and customer details</li><li>Reviews, coupons, offers and promotions</li><li>Shipping, payment and KYC future settings</li><li>Return/refund future activation area</li><li>Supabase/Auth/RLS security setup</li></ul></div>`,
products:()=>`<div class="split"><h2>Products</h2><button class="btn primary" onclick="$('#admin-content').innerHTML=productForm()">+ Add Product</button></div><div class="table-wrap panel"><table class="table"><thead><tr><th>Name</th><th>SKU</th><th>Price</th><th>Stock</th><th>Featured</th><th>Actions</th></tr></thead><tbody>${productRows()}</tbody></table></div>`,
orders:()=>{let o=read(KEYS.orders,[]);return `<div class="panel"><h2>Orders</h2><div class="table-wrap"><table class="table"><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Payment</th><th>Status</th><th>Actions</th></tr></thead><tbody>${o.map(x=>`<tr><td>${esc(x.id)}</td><td>${esc(x.customer_name)}<br>${esc(x.mobile)}<br>${esc(x.address_line)}, ${esc(x.city)}, ${esc(x.state)} ${esc(x.pincode)}</td><td>${money(x.total)}</td><td>${esc(x.payment_method)}<br>${esc(x.payment_status)}</td><td><select class=select onchange="setOrderStatus('${x.id}',this.value)">${["New","Confirmed","Packed","Shipped","Out for Delivery","Delivered","Cancelled","Returned","Refunded"].map(s=>`<option ${s===x.order_status?"selected":""}>${s}</option>`).join("")}</select></td><td><button class=btn onclick="verifyPayment('${x.id}')">Verify Payment</button></td></tr>`).join("")||"<tr><td colspan=6>No orders</td></tr>"}</tbody></table></div></div>`},
customers:()=>{let o=read(KEYS.orders,[]),map={};o.forEach(x=>map[x.mobile]=x);return `<div class="panel"><h2>Customers</h2><p class=muted>Customer information is private and should be backed by Supabase RLS in production.</p><div class=table-wrap><table class=table><thead><tr><th>Name</th><th>Mobile</th><th>Latest address</th><th>Latest order</th></tr></thead><tbody>${Object.values(map).map(x=>`<tr><td>${esc(x.customer_name)}</td><td>${esc(x.mobile)}</td><td>${esc(x.address_line)}, ${esc(x.city)}, ${esc(x.state)} - ${esc(x.pincode)}</td><td>${esc(x.id)}</td></tr>`).join("")}</tbody></table></div></div>`},
reviews:()=>`<div class="panel"><h2>Reviews</h2><p>Moderate written reviews, photos/videos, star ratings, verified purchase and helpful counts here when Supabase is connected.</p><button class="btn ok" onclick="alert('Review moderation interface is ready for Supabase records.')">Open Moderation</button></div>`,
categories:()=>`<div class="panel"><h2>Categories & Sub-categories</h2><div class="formgrid"><input class="input" placeholder="Category name"><input class="input" placeholder="Sub-category name"><input class="input" placeholder="Image URL"><input class="input" placeholder="Sort order"></div><button class="btn primary" style="margin-top:12px" onclick="alert('Category editor is ready; connect Supabase for persistent category records.')">Save Category</button></div>`,
coupons:()=>`<div class="panel"><h2>Coupons</h2><div class="formgrid"><input class="input" id=c-code placeholder="Coupon code"><select class=select id=c-type><option value=percent>Percent</option><option value=fixed>Fixed</option></select><input class=input id=c-value type=number placeholder="Value"><input class=input id=c-min type=number placeholder="Minimum order"><input class=input id=c-max type=number placeholder="Max discount"></div><button class="btn primary" style="margin-top:12px" onclick="saveCoupon()">Save Coupon</button><div id=coupon-list style="margin-top:18px"></div></div>`,
offers:()=>`<div class="panel"><h2>Offers & Promotions</h2><div class=formgrid><input class=input placeholder="Offer headline"><input class=input placeholder="Coupon code"><input class=input type=number placeholder="Discount %"><input class=input placeholder="Start/end dates"></div><button class="btn primary" style="margin-top:12px" onclick="alert('Offer saved in demo UI. Connect Supabase for persistent offers.')">Save Offer</button></div>`,
homepage:()=>`<div class="panel"><h2>Homepage Management</h2><p>Control which products appear and their order.</p>${products().map(p=>`<div class=split style="padding:10px 0;border-bottom:1px solid var(--line)"><span>${esc(p.name)}</span><input class=input style="max-width:120px" type=number value="${p.homepage_order||999999}" onchange="setHomeOrder('${p.id}',this.value)"><label><input type=checkbox ${p.featured?"checked":""} onchange="setFeatured('${p.id}',this.checked)"> Featured</label></div>`).join("")}</div>`,
banners:()=>`<div class="panel"><h2>Banners & Ads</h2><div class=formgrid"><input class="input full" placeholder="Banner image URL" value="banner.png"><input class="input full" placeholder="Promotion image/video URL"><input class="input" placeholder="Headline"><input class="input" placeholder="CTA text"></div><button class="btn primary" style="margin-top:12px" onclick="alert('Banner settings saved in demo UI. Persistent storage uses Supabase when connected.')">Save Banner / Ad</button></div>`,
settings:()=>{let s=read(KEYS.settings,{upi_id:"",whatsapp:"7903489053",email:"norvenofficial01@gmail.com",free_shipping_threshold:999,shipping_flat:60});return `<div class=panel><h2>Store Settings</h2><div class=formgrid><input id=s-upi class=input placeholder="UPI ID" value="${esc(s.upi_id||"")}"><input id=s-wa class=input placeholder="WhatsApp" value="${esc(s.whatsapp||"")}"><input id=s-email class=input placeholder="Email" value="${esc(s.email||"")}"><input id=s-free class=input type=number placeholder="Free shipping threshold" value="${s.free_shipping_threshold||999}"><input id=s-ship class=input type=number placeholder="Flat shipping" value="${s.shipping_flat||60}"><input class=input placeholder="Custom domain later"></div><button class="btn primary" style="margin-top:12px" onclick="saveSettings()">Save Settings</button></div>`},
shipping:()=>`<div class=panel><h2>Shipping Settings</h2><div class=formgrid><input class=input placeholder="Flat shipping ₹" value="60"><input class=input placeholder="Free shipping above ₹" value="999"><input class=input placeholder="Courier provider"><input class=input placeholder="Tracking API endpoint (future)"></div><p class=notice style="margin-top:12px">Third-party courier integration is intentionally future-ready. Delivery OTP should be handled by the courier provider unless NORVEN later operates its own delivery network.</p><button class="btn primary" onclick="alert('Shipping settings saved in demo UI.')">Save Shipping</button></div>`,
payments:()=>`<div class=panel><h2>KYC & Payments</h2><p>Future-ready area for payment gateway, KYC status and payout configuration.</p><div class=formgrid><input class=input placeholder="Gateway name"><input class=input placeholder="Merchant/public configuration"><input class=input placeholder="KYC status"><input class=input placeholder="Payout account status"></div><p class=notice style="margin-top:12px">Never place secret gateway keys in this static website. Real KYC must be completed with the payment provider/account holder.</p></div>`,
notifications:()=>`<div class=panel><h2>Notifications</h2><div class=formgrid><select class=select><option>Order placed</option><option>Order confirmed</option><option>Shipped</option><option>Out for Delivery</option><option>Delivered</option></select><input class=input placeholder="Email template / message"><input class=input placeholder="WhatsApp provider template"><input class=input placeholder="SMS provider template"></div><button class=btn primary style="margin-top:12px" onclick="alert('Notification configuration saved in demo UI.')">Save Notifications</button></div>`,
returns:()=>`<div class=panel><h2>Return & Refund — Future</h2><p class=notice>INACTIVE. Customer-facing return/refund controls are currently hidden exactly as requested.</p><div class=formgrid><select class=select><option>Disabled</option><option>Activate later</option></select><input class=input placeholder="Return window days"><input class=input placeholder="Refund method"><input class=input placeholder="Admin notes"></div></div>`,
security:()=>`<div class=panel><h2>Security / Backend</h2><ul><li>Supabase Auth for customer/admin accounts</li><li>RLS policies in supabase_schema.sql</li><li>Customer records limited to owner/customer via database policy</li><li>Admin role stored in profiles</li><li>Storage-ready product/banner/review media fields</li><li>No service-role secret in frontend</li></ul><p class=notice>Before real launch: configure Supabase, Auth, RLS, Storage, payment provider, courier API and notification provider.</p></div>`
};
function setOrderStatus(id,s){let o=read(KEYS.orders,[]),x=o.find(y=>y.id===id);if(x){x.order_status=s;write(KEYS.orders,o);refreshStats()}}
function verifyPayment(id){let o=read(KEYS.orders,[]),x=o.find(y=>y.id===id);if(x){x.payment_status="verified";write(KEYS.orders,o);renderSection("orders")}}
function setHomeOrder(id,v){let p=products(),x=p.find(y=>y.id===id);if(x){x.homepage_order=+v;write(KEYS.products,p);refreshStats()}}
function setFeatured(id,v){let p=products(),x=p.find(y=>y.id===id);if(x){x.featured=v;write(KEYS.products,p)}}
function saveCoupon(){let a=read(KEYS.coupons,[]);a.push({code:$("#c-code").value.toUpperCase(),type:$("#c-type").value,value:+$("#c-value").value,min_order:+$("#c-min").value||0,max_discount:+$("#c-max").value||null,active:true});write(KEYS.coupons,a);alert("Coupon saved");renderSection("coupons")}
function saveSettings(){write(KEYS.settings,{upi_id:$("#s-upi").value,whatsapp:$("#s-wa").value,email:$("#s-email").value,free_shipping_threshold:+$("#s-free").value||999,shipping_flat:+$("#s-ship").value||60});alert("Settings saved")}
document.addEventListener("DOMContentLoaded",()=>{if(isAdmin())showAdmin()})
