/* NORVEN storefront app. Demo mode works without Supabase. */
const DEMO_PRODUCTS=[
{id:"p1",name:"NORVEN Classic Hoodie",slug:"norven-classic-hoodie",price:899,mrp:1299,stock:20,sku:"NV-HOOD-01",category:"Fashion",subcategory:"Hoodies",images:["banner.png"],description:"Premium everyday hoodie for the NORVEN collection.",specifications:{Material:"Cotton blend",Fit:"Regular"},sizes:["S","M","L","XL"],colors:["Black","Cream"],rating:4.6,reviews_count:18,featured:true,homepage_order:1,active:true},
{id:"p2",name:"NORVEN Travel Backpack",slug:"norven-travel-backpack",price:749,mrp:999,stock:16,sku:"NV-BAG-01",category:"Gadgets",subcategory:"Bags",images:["banner.png"],description:"Everyday travel and creator-friendly backpack.",specifications:{Capacity:"25L",Material:"Polyester"},sizes:[],colors:["Black"],rating:4.5,reviews_count:12,featured:true,homepage_order:2,active:true},
{id:"p3",name:"NORVEN Everyday Watch",slug:"norven-everyday-watch",price:1199,mrp:1699,stock:8,sku:"NV-WATCH-01",category:"Watches",subcategory:"Everyday",images:["banner.png"],description:"Minimal everyday watch.",specifications:{Dial:"Analog",Strap:"PU"},sizes:[],colors:["Black"],rating:4.2,reviews_count:8,featured:false,homepage_order:3,active:true},
{id:"p4",name:"NORVEN Utility Bottle",slug:"norven-utility-bottle",price:349,mrp:499,stock:28,sku:"NV-BTL-01",category:"Home",subcategory:"Kitchen",images:["banner.png"],description:"Reusable utility bottle.",specifications:{Capacity:"750ml",Material:"Steel"},sizes:[],colors:["Black"],rating:4.3,reviews_count:7,featured:false,homepage_order:4,active:true}
];
const KEYS={products:"norven_products_v2",cart:"norven_cart_v2",wishlist:"norven_wishlist_v2",orders:"norven_orders_v2",profile:"norven_profile_v2",addresses:"norven_addresses_v2",coupons:"norven_coupons_v2",settings:"norven_settings_v2"};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function read(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
function write(k,v){localStorage.setItem(k,JSON.stringify(v))}
function products(){let p=read(KEYS.products,null);if(!p){p=DEMO_PRODUCTS;write(KEYS.products,p)}return p}
function cart(){return read(KEYS.cart,[])}
function setCart(v){write(KEYS.cart,v);updateCount()}
function updateCount(){let n=cart().reduce((a,x)=>a+x.qty,0);$$("[data-cart-count]").forEach(e=>e.textContent=n)}
function money(n){return "₹"+Number(n||0).toLocaleString("en-IN")}
function discount(p){return p.mrp?Math.max(0,Math.round((1-p.price/p.mrp)*100)):0}
function img(p){return (p.images&&p.images[0])||"logo.png"}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function productCard(p){return `<article class="card"><a href="product.html?id=${encodeURIComponent(p.id)}"><div class="card-img"><img src="${esc(img(p))}" alt="${esc(p.name)}"></div></a><div class="card-body"><div class="muted">${esc(p.category||"General")}</div><h3>${esc(p.name)}</h3><div><span class="price">${money(p.price)}</span>${p.mrp?`<span class="mrp">${money(p.mrp)}</span>`:""}${discount(p)?`<span class="discount">${discount(p)}% off</span>`:""}</div><div class="stars">★ ${p.rating||0} <span class="muted">(${p.reviews_count||0})</span></div><div class="actions" style="margin-top:10px"><button class="btn primary" onclick="event.preventDefault();addToCart('${p.id}')">Add to Cart</button><button class="btn" onclick="event.preventDefault();toggleWish('${p.id}')">♡</button></div></div></article>`}
function addToCart(id){let p=products().find(x=>x.id===id);if(!p||p.stock<1)return alert("Product is out of stock.");let c=cart(),x=c.find(i=>i.id===id);x?x.qty=Math.min(x.qty+1,p.stock):c.push({id,qty:1});setCart(c);alert("Added to cart")}
function toggleWish(id){let w=read(KEYS.wishlist,[]);w=w.includes(id)?w.filter(x=>x!==id):[...w,id];write(KEYS.wishlist,w);alert(w.includes(id)?"Added to wishlist":"Removed from wishlist")}
function header(){return `<header class="topbar"><div class="container nav"><a class="brand" href="index.html">N O R V E N <small>Shop</small></a><div class="nav-spacer"></div><a class="nav-btn" href="account.html"><span class="ico">👤</span><span>Account</span></a><a class="nav-btn" href="cart.html"><span class="ico">🛒</span><span>Cart</span><span class="count" data-cart-count>0</span></a></div></header>`}
function footer(){return `<footer class="footer"><div class="container footer-grid"><div><b>NORVEN</b><p>New Vision Everyday Needs</p></div><div><b>Customer</b><p><a href="account.html">Account & Orders</a></p><p><a href="policies.html">Policies</a></p></div><div><b>Company</b><p><a href="about.html">About</a></p><p><a href="contact.html">Contact</a></p></div><div><b>Support</b><p><a href="https://wa.me/917903489053">WhatsApp</a></p><p>norvenofficial01@gmail.com</p></div></div></footer>`}
function boot(){updateCount();let h=$("#site-header");if(h)h.innerHTML=header();let f=$("#site-footer");if(f)f.innerHTML=footer()}
function renderHome(){let list=products().filter(p=>p.active!==false).sort((a,b)=>(a.homepage_order||999999)-(b.homepage_order||999999));let cats=[...new Set(list.map(p=>p.category).filter(Boolean))];$("#cats").innerHTML=`<button class="chip active" data-cat="All">All</button>`+cats.map(c=>`<button class="chip" data-cat="${esc(c)}">${esc(c)}</button>`).join("");let grid=$("#product-grid"),search=$("#search"),sort=$("#sort"),active="All";function draw(){let q=(search.value||"").toLowerCase();let a=list.filter(p=>(active==="All"||p.category===active)&&(!q||`${p.name} ${p.category} ${p.sku}`.toLowerCase().includes(q)));if(sort.value==="price-low")a.sort((x,y)=>x.price-y.price);if(sort.value==="price-high")a.sort((x,y)=>y.price-x.price);if(sort.value==="rating")a.sort((x,y)=>(y.rating||0)-(x.rating||0));grid.innerHTML=a.length?a.map(productCard).join(""):`<div class="empty full">No products found.</div>`}$("#cats").onclick=e=>{let b=e.target.closest("[data-cat]");if(!b)return;active=b.dataset.cat;$$(".chip").forEach(x=>x.classList.remove("active"));b.classList.add("active");draw()};search.oninput=draw;sort.onchange=draw;draw()}
document.addEventListener("DOMContentLoaded",()=>{boot();if($("#home"))renderHome()})
