create extension if not exists pgcrypto;
create type public.order_status as enum ('new','confirmed','packed','shipped','out_for_delivery','delivered','cancelled','returned','refunded');
create type public.user_role as enum ('customer','admin');
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text,mobile text,role public.user_role not null default 'customer',created_at timestamptz default now());
create table if not exists public.categories(id uuid primary key default gen_random_uuid(),name text not null,parent_id uuid references public.categories(id),sort_order int default 0,active boolean default true);
create table if not exists public.products(id uuid primary key default gen_random_uuid(),name text not null,description text,specifications jsonb default '{}'::jsonb,category_id uuid references public.categories(id),price numeric(12,2) not null default 0,mrp numeric(12,2),discount_percent numeric(6,2),stock int not null default 0,sku text unique,sizes jsonb default '[]',colors jsonb default '[]',video_url text,featured boolean default false,homepage_visible boolean default false,homepage_order int default 0,active boolean default true,created_at timestamptz default now());
create table if not exists public.product_images(id uuid primary key default gen_random_uuid(),product_id uuid references public.products(id) on delete cascade,image_url text not null,sort_order int default 0);
create table if not exists public.addresses(id uuid primary key default gen_random_uuid(),user_id uuid references auth.users(id) on delete cascade,full_name text,mobile text,address text,city text,state text,pin text,created_at timestamptz default now());
create table if not exists public.orders(id uuid primary key default gen_random_uuid(),user_id uuid references auth.users(id),status public.order_status default 'new',total numeric(12,2) default 0,payment_method text,payment_status text,payment_reference text,shipping_name text,shipping_mobile text,shipping_address text,shipping_city text,shipping_state text,shipping_pin text,tracking_number text,courier_name text,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.order_items(id uuid primary key default gen_random_uuid(),order_id uuid references public.orders(id) on delete cascade,product_id uuid references public.products(id),product_name text,quantity int,unit_price numeric(12,2));
create table if not exists public.reviews(id uuid primary key default gen_random_uuid(),product_id uuid references public.products(id) on delete cascade,user_id uuid references auth.users(id),rating int check(rating between 1 and 5),body text,verified_purchase boolean default false,helpful_count int default 0,approved boolean default false,created_at timestamptz default now());
create table if not exists public.review_media(id uuid primary key default gen_random_uuid(),review_id uuid references public.reviews(id) on delete cascade,media_url text,media_type text);
create table if not exists public.coupons(id uuid primary key default gen_random_uuid(),code text unique,discount_type text,value numeric,min_order numeric default 0,expires_at timestamptz,active boolean default true);
create table if not exists public.store_settings(id boolean primary key default true,logo_url text,banner_url text,upi_id text,qr_url text,whatsapp text,email text,free_shipping_min numeric,shipping_charge numeric,return_refund_enabled boolean default false);
create table if not exists public.homepage_sections(id uuid primary key default gen_random_uuid(),title text,section_type text,sort_order int default 0,active boolean default true,config jsonb default '{}'::jsonb);
create table if not exists public.banners(id uuid primary key default gen_random_uuid(),image_url text,video_url text,link_url text,sort_order int default 0,active boolean default true);
create table if not exists public.notifications(id uuid primary key default gen_random_uuid(),user_id uuid references auth.users(id),order_id uuid references public.orders(id),type text,title text,body text,read boolean default false,created_at timestamptz default now());
-- Enable RLS on every production table and create customer-self/admin-only policies before launch.
-- Do not rely on hidden UI for security. Admin permissions must be server-side enforced.
-- Customer return/refund UI remains disabled while return_refund_enabled is false.
